### ISSUE TITLE
Question: Does this change apply to emqtt

### ISSUE THREAD

**Issue by parberge** [wicol/emqtt#4]
mqtt platform in hass was updated recently:
```
The default availability payloads for the MQTT switch platform have changed from “ON” and “OFF” to “online” and “offline” (in order to match the majority of MQTT platforms that already supported availability reporting). (@DanNixon - #11336) (breaking change)
```
https://github.com/home-assistant/home-assistant/pull/11336

I'm not sure if this mean the PAYLOAD should be "online" and "offline" instead of "ON" and "OFF"

**Comment by wicol** [comment]
Short answer is nope. Long answer is payload_on and payload_off default values are still "ON" and "OFF" (docs are wrong: https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/binary_sensor/mqtt.py#L28). The change is related to the availability topic.

This does however spark the idea of offering availability information for emqtt clients...
