### ISSUE TITLE
Request: Add proper license

### ISSUE THREAD

**Issue by holgersson32644** [wicol/emqtt#5]
Hi,
your bridge is quite helpful. I'd like to package (and mirror) it; to do so in a legal way I need a license information:

Can you please select a license for your project and add the license file e.g. as LICENSE and with a short copyright + LICENSE note into the actual source code?

Thanks in advance

**Comment by wicol** [comment]
That's nice to hear!
Sorry about the response time, I don't check in on github notifications often enough. I went for MIT because it's popular. Hope that works.
Let me know what you end up using it for :)
