### ISSUE TITLE
emqtt errors on publish if MQTT_PORT is defined in docker

### ISSUE THREAD

**Issue by ristomatti** [wicol/emqtt#6]
Initially I had `MQTT_PORT` set to its default value 1883 but emqtt then throws the below error from paho when it tries to publish:
```
TypeError: '<=' not supported between instances of 'str' and 'int'
```

I don't have the full stack easily on hand now as I already worked around the issue by not defining the port. I assume what happens is that the environment variable is being read as a string and not a number.

Unfortunately I have no python experience so I cannot easily create a PR on this.

**Comment by wicol** [comment]
oops, I need to get my notifications sorted.. I'll get this fixed asap :)
