### ISSUE TITLE
Fails to run with recent versions of aiosmtpd

### ISSUE THREAD

**Issue by l3nticular** [wicol/emqtt#9]
Image on docker hub is for linux/amd64; so I locally built this for my Pi4 and it fails to run.  I suspect it's due to updated Alpine.

Creating emqtt ... done
Attaching to emqtt
emqtt    | 2021-04-10 04:17:31,523 - emqtt - INFO - Setting up a filehandler
emqtt    | 2021-04-10 04:17:31,524 - emqtt - INFO - Configured to save attachments
emqtt    | Exception in thread Thread-1:
emqtt    | Traceback (most recent call last):
emqtt    |   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
emqtt    |     self.run()
emqtt    |   File "/usr/lib/python3.8/threading.py", line 870, in run
emqtt    |     self._target(*self._args, **self._kwargs)
emqtt    |   File "/usr/lib/python3.8/site-packages/aiosmtpd/controller.py", line 169, in _run
emqtt    |     asyncio.set_event_loop(self.loop)
emqtt    |   File "/usr/lib/python3.8/asyncio/events.py", line 753, in set_event_loop
emqtt    |     get_event_loop_policy().set_event_loop(loop)
emqtt    |   File "/usr/lib/python3.8/asyncio/unix_events.py", line 1365, in set_event_loop
emqtt    |     super().set_event_loop(loop)
emqtt    |   File "/usr/lib/python3.8/asyncio/events.py", line 647, in set_event_loop
emqtt    |     assert loop is None or isinstance(loop, AbstractEventLoop)
emqtt    | AssertionError

**Comment by wicol** [comment]
Thanks for the fix!
